quarkus:
  # datasource configuration
  datasource:
    db-kind: postgresql
    username: postgres
    password: admin
    jdbc:
      url: jdbc:postgresql://localhost:5432/newsletter-erro
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    port: 8082